# Generated by Django 3.0.3 on 2020-03-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20200227_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'business_times',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.City')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='FavoriteStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'db_table': 'favorite_stores',
            },
        ),
        migrations.CreateModel(
            name='ServiceOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, null=True)),
                ('icon_url', models.URLField(max_length=2000, null=True)),
                ('thumbnail_url', models.URLField(max_length=2000, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'services_one',
            },
        ),
        migrations.CreateModel(
            name='ServiceTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, null=True)),
                ('icon_url', models.URLField(max_length=2000, null=True)),
                ('thumbnail_url', models.URLField(max_length=2000, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'services_two',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store_code', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=50, null=True)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=50, null=True)),
                ('street_name', models.CharField(max_length=200)),
                ('account', models.ManyToManyField(through='store.FavoriteStore', to='account.Account')),
                ('business_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.BusinessTime')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.City')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.District')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreServiceTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ServiceTwo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'db_table': 'stores_services_two',
            },
        ),
        migrations.CreateModel(
            name='StoreServiceOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ServiceOne')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'db_table': 'stores_services_one',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='service_one',
            field=models.ManyToManyField(through='store.StoreServiceOne', to='store.ServiceOne'),
        ),
        migrations.AddField(
            model_name='favoritestore',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
