# Generated by Django 3.0.3 on 2020-02-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200225_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='natrium',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='offer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar',
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
    ]
