# Generated by Django 3.0.3 on 2020-02-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200225_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='natrium',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar',
            field=models.CharField(max_length=200),
        ),
    ]
