# Generated by Django 3.0.3 on 2020-02-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200225_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutrition',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
