# Generated by Django 3.0.3 on 2020-02-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200225_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=200)),
                ('calories', models.CharField(max_length=200)),
                ('natrium', models.CharField(max_length=200)),
                ('sugar', models.CharField(max_length=200)),
                ('fat', models.CharField(max_length=200)),
                ('protein', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Nutrition'),
        ),
    ]
