# Generated by Django 3.0.3 on 2020-02-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200225_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
    ]
