# Generated by Django 3.0.3 on 2020-03-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_size_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
        migrations.CreateModel(
            name='ProductIcecreamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_product', to='product.Product')),
                ('to_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_product', to='product.Product')),
            ],
            options={
                'db_table': 'products_icecream_members',
                'unique_together': {('from_product', 'to_product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='icecream_member',
            field=models.ManyToManyField(through='product.ProductIcecreamMember', to='product.Product'),
        ),
    ]
