# Generated by Django 3.0.3 on 2020-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200302_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductIcecreamMember',
            new_name='ProductFlavor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icecream_member',
        ),
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.ManyToManyField(through='product.ProductFlavor', to='product.Product'),
        ),
        migrations.AlterModelTable(
            name='productflavor',
            table='products_flavors',
        ),
    ]
